FROM ubuntu

RUN apt-get clean && apt-get update && apt-get install -y \
    curl

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

RUN apt-get upgrade -y

COPY . .

RUN npm install

ENTRYPOINT ["node", "index.js"]
